# autogenerated by txs
#include:balance
#include:caption2
#include:fancyhdr
#include:lastpage
#include:latex-document
#include:tex
#include:times
\abstracttext{arg1}#S
\affiliation{arg1}#S
\bibfont#S
\copyrightspace#S
\firstpage{arg1}#S
\maketitle#S
\pubyear{arg1}#S
\volume{arg1}#S
