#!/usr/bin/perl

use warnings;
use strict;

open (FN, '<', "foot");

my %fnseen = ();
my %notes = ();

my $page = '';
my $note = '';

my $sent = '';
my $rest = '';

while (<FN>) {
	if (m!<a id="footnote([^_]*)_([^"]*)" name="footnote[^_]*_[^"]*">!) {
		$page = $2;
		$note = $1;
	} elsif (m!<div class="note"><p>([^<]*)</p></div>!) {
		$notes{"p{$page}_n{$note}"} = $1;
print "p{$page}_n{$note} = " . $notes{"p{$page}_n{$note}"} . "\n";
	} else {
		next;
	}
}

